JJOBO/6-Docthru-3team-BE

README.md, package.json
fix: package.json 스크립트에 start 추가
=> fix: package.json 스크립트에 start 추가

src/app.js, src/routes/challenge.route.js, src/routes/user.route.js, src/routes/work.route.js
chore: app.js 복수형네이밍적용 & 각 route에서 :id 상세네이밍적용
=> chore: app.js 복수형네이밍적용 & 각 route에서 :id 상세네이밍적용

src/prisma/schema.prisma
알림 isRead 필드 추가 & 챌린지 docType 필드 이름 변경 & 작업물 불필요한 필드 제거했습니다.
=> fix: 알림 isRead 필드 추가 & 챌린지 docType 필드 이름 변경 & 작업물 불필요한 필드 제거

src/prisma/migrations/20250520014811_new_migration/migration.sql, src/prisma/schema.prisma, src/prisma/seed/seed.js
fix: 스키마 변경사항 250520 회의내용
- maxWorkCount -> maxParticipant로 적용
- 관계형 id필드 위치 이동
- Work 모델의 title 필드 제거
- providerId 필드 추가
- refreshToken 필드 추가
=> fix: 스키마 변경사항 250520 회의내용

http/auth.http, http/challenge.http, rest-client.env.json, src/controllers/challenge.controller.js, src/repositories/challenge.repository.js, src/routes/challenge.route.js, src/services/challenge.service.js
- 챌린지 상세조회
- 챌린지 수정
- 챌린지 삭제
권한 관련 코드 추가했습니다.
@suKyoung25 
챌린지 목록조회 코드가 없으면 에러가 나서 ㅠㅠ 대충 gpt로 긁어서 넣었습니다.
필요시 삭제하세요!
=> 챌린지 id조회/수정/삭제 api 구현

src/controllers/challenge.controller.js, src/routes/challenge.route.js
- 기존 코드가 섞여서 버그났던 부분 수정했습니다.
- 라우트 import 누락된 부분 보완했습니다.
=> 챌린지 컨트롤러, 라우트 수정

http/admin-work.http, src/controllers/admin.controller.js, src/controllers/work.controller.js, src/repositories/work.repository.js, src/routes/admin.route.js, src/routes/work.route.js, src/services/work.service.js
Work 소프트삭제 & 하드삭제 API 작동 확인했습니다.
- 토큰이 존재할때 직접삭제 기능, 그리고 토큰존재시 소프트삭제(비활성화 처리)하는 admin 전용 기능도 작동 확인했습니다.
- 소프트삭제시 응답메시지
=> feat: Work 소프트삭제 & 하드삭제 API 작동 확인

http/feedback.http, http/work.http, src/routes/challenge.route.js, src/routes/work.route.js
- 작업물상세조회&제출 엔드포인트 구현완료했습니다. (응답메시지는 노션 API명세서에 작성해두었습니다.)
- 작업물상세조회시 요청에 엑세스토큰 포함하도록 개선했습니다.
=> feat: 작업물상세조회&제출 엔드포인트 구현완료&작업물상세조회시 요청에 엑세스토큰 포함

http/admin.http, http/challenge.http, src/repositories/challenge.repository.js
=> modify: 어드민 신청 관리 invalidatedAt 로직 수정

http/auth.http, http/work.http, src/controllers/work.controller.js, src/repositories/work.repository.js, src/routes/challenge.route.js, src/routes/work.route.js, src/services/work.service.js
- 현재 챌린지의 work 조회시에 페이지네이션 기능으로 조회 되도록 수정했습니다.
- work의 모든 api 경로에 token 로직을 적용 및 테스트하였습니다.
=> faet : work api token 로직 확인 및 work 조회 pagination 기능 추가

src/prisma/migrations/20250523011118_nickname_unique/migration.sql, src/prisma/schema.prisma
User 모델 nickname필드 unique속성 추가, DB적용했습니다.
=> feat: User 모델 nickname필드 unique속성 추가

http/admin.http, http/auth.http, http/challenge.http, http/feedback.http, http/work.http, src/app.js, src/controllers/challenge.controller.js, src/repositories/challenge.repository.js, src/repositories/work.repository.js, src/routes/work.route.js, src/services/challenge.service.js, src/services/feedback.service.js
notification.http
user.http 를 제외한 모든 API confirm 완료입니다.
pull 받으시고 본인 파트 수정해주시면 감사하겠습니다.
=> API 전체 confirm

package-lock.json, src/app.js, src/repositories/challenge.repository.js, src/repositories/user.repository.js
- 내가 신청한 챌린지 api 불러올 때 adminStatus 불러오도록 관련 코드를 추가했습니다.
=> 내가 신청한 챌린지 api 불러올 때 adminStatus 불러오도록 추가

src/repositories/challenge.repository.js
죄송합니다 코드에 이미지 필드를 넣어서 삭제했습니다 ..
=> fix: findChallengeDetailById에서 잘못된 필드 삭제

src/repositories/challenge.repository.js
=> fix:findChallengeDetailById에 participants필드 추가

src/controllers/user.controller.js, src/repositories/user.repository.js, src/services/user.service.js
- 나의 챌린지 api 중 페이지네이션에 필요한 데이터를 위해 코드를 수정했습니다
- 데이터를 불러올 때 최신순으로 불러오도록 코드를 수정했습니다
=> 나의 챌린지 페이지네이션 코드 보완

src/controllers/auth.controller.js
getChallenges 임포트오류 개 선 & 로그인버튼 비활성화 개선했습니다.
- 결과: 로그인버튼으로 로그인이 잘 됩니다.
- 챌린지목록에서 getChallenges 관련 임포트 경로를 개선하여 화면진입시 오류가 나지 않게 되었습니다.
=> fix: getChallenges 임포트오류 개 선 & 로그인버튼 비활성화 개선

src/controllers/challenge.controller.js, src/repositories/challenge.repository.js, src/services/challenge.service.js
- 관리자만 챌린지를 수정/삭제 할 수 있도록 코드를 수정했습니다.
=> 관리자만 챌린지 수정/삭제 가능하도록 수정

http/admin.http, http/auth.http, src/controllers/auth.controller.js
쿠키옵션 수정 & admin,auth http 테스트중인 어드민 request 요청값 유지했습니다.
=> fix: 쿠키옵션 수정

http/auth.http, http/user.http, src/controllers/user.controller.js, src/exceptions/ExceptionMessage.js, src/repositories/user.repository.js, src/routes/user.route.js, src/services/user.service.js
- 나의 챌린지 신청 상세 조회와 어드민 신청 상세 조회 페이지를 구현하기 위해 백엔드 API를 추가했습니다.
=> Feat/application 신청 상세 조회 구현

src/controllers/user.controller.js, src/repositories/challenge.repository.js, src/repositories/user.repository.js
- 챌린지 전체 조회 - `application` 전체 필드 포함
- 나의 신청한 챌린지 전체 조회 - `application `전체 필드 포함
- 신청 챌린지 상세 조회 - `challenge` participants 수 포함
=> modify: 신청한 챌린지 상세 정보 포함

http/challenge.http, src/controllers/challenge.controller.js, src/repositories/challenge.repository.js
- 기존 코드 
status(챌린지의 마감/진행중) 없음 
- 수정된 코드
repository단에서 deadline과 maxparticipant 계산하여 status 응답 추가
=> feat: 챌린지 목록 가져오는 엔드포인트 수정

src/services/feedback.service.js
=> feat: 피드백삭제하는 유저가 어드민일 시 삭제 허용로직 추가

src/repositories/challenge.repository.js
- 기존 코드
options로 전달되고있는 category가 1개씩밖에 전달 안되고 있던 상황
- 수정된 코드
...&category=Next.js&category=Morder.js 이런식으로 다중 쿼리가 가능하도록 수정
=> fixed: 필터 중복 되도록 수정

http/challenge.http, src/repositories/challenge.repository.js
=> add: 띄어쓰기 & 초성검색 기능 추가

src/repositories/notification.repository.js, src/services/notification.service.js
notification 읽음처리 관련 코드 수정했습니다
=> fix notification

src/prisma/migrations/20250530063558_most_recommended_count/migration.sql, src/prisma/migrations/20250530064823_is_closed/migration.sql, src/prisma/schema.prisma
=> feat: Challenge모델 isClosed필드 추가

http/user.http, src/repositories/user.repository.js
=> modify: authorId와 userId 같은 work만 찾도록 수정

src/services/challenge.service.js, src/services/user.service.js, src/services/work.service.js
유저의 등업기능을 위해 필요한 함수들을 추가했습니다.
```jsx
import prisma from "../prisma/client.prisma.js";
export const tryUpgradeUserGrade = async (userId) => {
const user = await prisma.user.findUnique({
where: { id: userId },
include: { works: true },
});
if (!user || user.grade === "EXPERT") return;
const workCount = user.works.length;
const mostRecommendedCount = user.mostRecommendedCount;
const isExpert =
(mostRecommendedCount >= 5 && workCount >= 5) ||
mostRecommendedCount >= 10 ||
workCount >= 10;
if (isExpert) {
await prisma.user.update({
where: { id: userId },
data: { grade: "EXPERT" },
});
}
};
```
```jsx
import { tryUpgradeUserGrade } from "./user.service.js";
async function closeAndSelectTopWork(challengeId) {
const challenge = await challengeRepository.findChallengeDetailById(challengeId);
if …
```
=> feat:유저의 등업기능을 위해 필요한 함수를 추가

src/services/feedback.service.js
=> fix: 피드백서비스 삭제로직 개선

src/controllers/challenge.controller.js
=> add: 챌린지 컨트롤러에서 겟챌린지바이아이디 함수에 챌린지가 승인되지 않은경우 url을 통해 접근하는것을 제한하는 함수 추가

http/auth.http
=> fix: 마이그레이션 중간 저장

src/services/notification.service.js
=> 승인 부분 한글로 변환되도록 수정

src/controllers/auth.controller.js
기존 백엔드에서 쿠키저장후 리디렉션시키는 로직 제거 -> 쿠키 생성 후 `json` 응답만 반환
=> fix: 구글로그인 에러 리디렉션 프론트 처리

src/services/challenge.service.js
=> 챌린지 신청 관리 - 어드민 부분 에러처리 강화
